name: tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install packages
      run: pip install -r requirements.txt black flake8 isort
    - name: Run linters
      run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.7, 3.6, 3.5]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install packages
      run: pip install -r requirements.txt coverage
    - name: Run test suite
      run: make test
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
